Remove tgz files from gem package
fhir-crucible/fhir_models pull request #119
Opened 2024-10-15 14:05 UTC by jlduran

There is a considerable file size increase for 5.0.0:

[5.0.0](https://rubygems.org/gems/fhir_models/versions/5.0.0) - October 14, 2024 (36.7 MB)
[4.3.0](https://rubygems.org/gems/fhir_models/versions/4.3.0) - May 30, 2024 (7.51 MB)

Mainly due to the inclusion of compressed artifacts:

- [hl7.fhir.r4.core.tgz](https://github.com/fhir-crucible/fhir_models/commit/3a964f75102b0ee69f2b8191c80f9ecd6ca91bab#diff-c0ff0624476e0ee9430aea7b151f6618c3d0ca6ab05689d29f25322b1264dc78)
- [hl7.fhir.r4b.core.tgz](https://github.com/fhir-crucible/fhir_models/commit/3a964f75102b0ee69f2b8191c80f9ecd6ca91bab#diff-c68fdc42bd1b99c0d1ea7c357b9891427ce0a1613a9bca88fb23a02f16fe0aad)
- [hl7.fhir.r5.core.tgz](https://github.com/fhir-crucible/fhir_models/commit/1924f6bcf5432708e4df8418c5ac119b4fbc80db)

Avoid it by excluding these files from the final gem package.

2026-05-04 17:32 UTC, karlnaden requested changes

2026-05-04 17:32 UTC, karlnaden commented on fhir_models.gemspec
> +  spec.files.reject! { |file| file =~ /.*\.tgz$/}
Reasoning is sound, but for the implementation, let's exclude the whole igs directory from the gem. Those files are needed only for generation during development, not for use when importing as a gem. Update to exclude the whole directory and we can get this update incorporated.

2026-05-04 17:59 UTC, jlduran commented on fhir_models.gemspec
> +  spec.files.reject! { |file| file =~ /.*\.tgz$/}
Sounds good. Done!

2026-05-05 11:49 UTC, karlnaden requested changes
small last cleanup, then will get merged in and released - thanks

2026-05-05 11:49 UTC, karlnaden commented on fhir_models.gemspec
> +  spec.files.reject! { |file| file =~ /package_supplement\/expansions.json/}
package_supplement is under the igs folder, so this line is not needed any

```suggestion
```

2026-05-05 16:23 UTC, karlnaden approved these changes

2026-05-05 16:23 UTC, jlduran commented
Thank you @karlnaden. I've applied your suggestions and submitted a few additional PRs. I'd appreciate it if you could take a look at those as well when you have a moment.

2026-05-05 16:24 UTC, merged

2026-05-05 16:25 UTC, karlnaden commented
> Thank you @karlnaden. I've applied your suggestions and submitted a few additional PRs. I'd appreciate it if you could take a look at those as well when you have a moment.

This one is merged. Will try to review the additional PRs later this week and get a gem out.